
Issue that I've been involved with as part of this particular project.


| Python issue                       | Title                                                                                                | Issue type               | Fix                                          |
|------------------------------------|------------------------------------------------------------------------------------------------------|--------------------------|----------------------------------------------|
| https://bugs.python.org/issue29924 | Useless argument in call to PyErr_Format                                                             | Code quality             | https://github.com/python/cpython/pull/854   |
| https://bugs.python.org/issue29932 | Missing word ("be") in error message ("first argument must a type object")                           | Error message            | https://github.com/python/cpython/pull/888   |
| https://bugs.python.org/issue30592 | Bad error message 'bool()() takes no keyword arguments'                                              | Error message/regression | https://github.com/python/cpython/pull/1996  |
| https://bugs.python.org/issue30600 | Error message incorrect when index is called with keyword argument ("[].index(x=2)")                 | Argument clinic          | https://github.com/python/cpython/pull/2051  |
| https://bugs.python.org/issue30627 | Incorrect error message for a few functions called with keywod argument                              | Argument handling        | https://github.com/python/cpython/pull/2115  |
| https://bugs.python.org/issue35965 | Behavior for unittest.assertRaisesRegex differs depending on whether it is used as a context manager | Invalid issue            |                                              |
| https://bugs.python.org/issue36026 | Different error message when sys.settrace is used                                                    | Error message            | https://github.com/python/cpython/pull/11930 |
| https://bugs.python.org/issue30878 | The staticmethod doesn't properly reject keyword arguments                                           | Argument handling        | https://github.com/python/cpython/pull/2635  |
